version: '3.4'

services:
  tesseractapi:
    image: ${DOCKER_REGISTRY-}tesseractapi
    build:
      context: .
      # uncomment to build image with additional languages
      #args:
      # - OCR_LANGS=eng+por+rus
      dockerfile: TesseractApi/Dockerfile
